const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const path = require( 'path' );

/**
 * Two editor entry points, built into build/editor.js and build/settings.js
 * (each with a matching *.asset.php dependency manifest, auto-generated by
 * @wordpress/dependency-extraction-webpack-plugin, already wired into the
 * default @wordpress/scripts config).
 *
 * Run `npm run build` once after `npm install` to generate the build/ folder.
 * Run `npm start` while developing to rebuild on every save.
 */
module.exports = {
	...defaultConfig,
	entry: {
		editor: path.resolve( process.cwd(), 'src', 'editor.js' ),
		settings: path.resolve( process.cwd(), 'src', 'settings.js' ),
	},
};
